export const GET_MAX_CREDITS = 'GET_MAX_CREDITS';
export const GET_MAX_CREDITS_ERROR = 'GET_MAX_CREDITS_ERROR';
export const BET_REQUEST = 'BET_REQUEST';
export const BET_SUCCESS = 'BET_SUCCESS';
export const BET_ERROR = 'BET_ERROR';

export const SET_PUBLICKEY = 'SET_PUBLICKEY';

export const GET_TRANSACTION_HISTORY_SUCCESS = 'GET_TRANSACTION_HISTORY_SUCCESS';
export const GET_TRANSACTION_HISTORY_ERROR = 'GET_TRANSACTION_HISTORY_ERROR';

export const TRANSACTION_TYPE = {
    WITHDRAW: 'Withdraw',
    DEPOSIT: 'Deposit',
    REWARDS: 'Rewards',
    NONE: ''
}